# Generated by Django 4.2.4 on 2023-08-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='avatar'),
        ),
    ]
